import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  imageBackground: {
    flex: 1,
    resizeMode: 'cover',
  },
  background: {
    backgroundColor: 'rgba(228, 172, 234, 1)',
  },

  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 50,
  },

  mapContainer: {
    flex: 1,
  },

  textContainer: {
    marginTop: 50,
    alignSelf: 'center',
    width: '90%',
    padding: 20,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowRadius: 4,
    bottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  header: {
    color: '#333',
    paddingHorizontal: 20,
    marginTop: 20,
    fontSize: 16,
    textAlign: 'center',
  },
  text: {
    fontFamily: 'Capriola-Regular',
  },
  letterText: {
    fontSize: 30,
    color: '#333',
    textAlign: 'center',
    fontFamily: 'Jua-Regular',
    flexWrap: 'wrap',
  },
  postInteractionText: {
    color: '#333',
    fontSize: 16,
  },
  imageStyle: {
    width: '100%',
    height: 250,
    borderRadius: 10,
    marginBottom: 15,
  },
  imageContainer: {
    margin: 20,
    flexDirection: 'column',
    padding: 20,
    borderRadius: 15,
    shadowOpacity: 0.4,
    shadowRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    width: '90%',
  },
  commentInput: {
    width: '100%',
    minHeight: 45,
    marginBottom: 10,
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.8)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
  },
  CameraContainer: {
    flex: 1,
  },
  cameraPageContainer: {
    flex: 1,
    backgroundColor: '#222',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 40,
  },
  cameraPageBtn: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#444',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nativeCameraButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 20,
    padding: 8,
  },
  previewOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 24,
  },
  previewImage: {
    width: '90%',
    height: '65%',
    borderRadius: 12,
  },
  previewActions: {
    flexDirection: 'row',
    gap: 16,
  },
  previewBtn: {
    alignItems: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  previewBtnPrimary: {
    backgroundColor: '#3388ff',
  },
  previewBtnSecondary: {
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  previewBtnText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  camera: {
    flex: 1,
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 50,
    alignSelf: 'center',
  },
  CameraButtons: {
    position: 'absolute',
    flexDirection: 'row',
    bottom: 25,
    alignSelf: 'center',
    gap: 50,
  },
  captureButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'pink',
    borderWidth: 5,
    borderColor: 'gray',
  },
  permissionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  permissionButton: {
    marginTop: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: '#007AFF',
    borderRadius: 8,
  },
  permissionButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  map: {
    flex: 1,
  }, // värit taustalle #B5DACE, #ECC0D1
  cameraButton: {
    position: 'absolute',
    bottom: 40,
    right: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#3388ff',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  cameraButtonDisabled: {
    backgroundColor: '#9e9e9e',
  },
  cameraIcon: {
    fontSize: 26,
  },
  locateButton: {
    position: 'absolute',
    bottom: 116,
    right: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  locateButtonActive: {
    backgroundColor: '#3388ff',
  },
  locateIcon: {
    fontSize: 26,
  },
  streakBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    backgroundColor: '#ff6f00',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  streakBadgeDead: {
    backgroundColor: '#757575',
  },
  streakText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  taskBanner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(46,125,50,0.92)',
    paddingVertical: 12,
    alignItems: 'center',
  },
  taskBannerText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  previewBtnSuccess: {
    backgroundColor: '#2e7d32',
  },
  newsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  newsButton: {
    backgroundColor: '#e885c2',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  newsText: {
    flex: 1,
    flexShrink: 1,
    marginRight: 5,
  },
  // Settings
  settingsContainer: {
    padding: 24,
    gap: 24,
  },
  settingsSection: {
    gap: 12,
  },
  settingsSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  settingsSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#555',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 16,
  },
  settingsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  settingsCard: {
    width: '47%',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 2.5,
    borderColor: 'transparent',
    backgroundColor: 'rgba(255,255,255,0.35)',
  },
  settingsCardActive: {
    borderColor: '#333',
  },
  settingsPreview: {
    height: 64,
  },
  settingsLabel: {
    padding: 10,
    fontSize: 15,
    fontWeight: '500',
    color: '#333',
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  settingsRowLabel: {
    fontSize: 15,
    color: '#333',
    fontWeight: '500',
  },
  settingsOptionRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  settingsOptionBtn: {
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#bbb',
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  settingsOptionBtnActive: {
    borderColor: '#333',
    backgroundColor: 'rgba(0,0,0,0.08)',
  },
  settingsOptionBtnText: {
    fontSize: 13,
    color: '#444',
  },
  settingsOptionBtnTextActive: {
    fontWeight: '700',
    color: '#111',
  },
  settingsStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingsStepperBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#bbb',
    backgroundColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsStepperBtnText: {
    fontSize: 18,
    color: '#333',
    lineHeight: 22,
  },
  settingsStepperValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    minWidth: 24,
    textAlign: 'center',
  },
  settingsNameInput: {
    borderWidth: 1.5,
    borderColor: '#bbb',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#333',
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  settingsSaveBtn: {
    flexDirection: 'row',
    alignSelf: 'flex-end',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 7,
    paddingHorizontal: 18,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#999',
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  settingsSaveBtnSaved: {
    borderColor: '#1a7a3f',
    backgroundColor: 'rgba(26,122,63,0.1)',
  },
  settingsSaveBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  settingsSaveBtnTextSaved: {
    color: '#1a7a3f',
  },
});
