import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  background: {
    backgroundColor: "#E4ACEA",
  },
  container: {
    flex: 1,
    flexDirection: "column",
  },
  TextContainer: {
    marginTop: 50,
    alignSelf: "center",
    width: "90%",
    backgroundColor: "#ffbff2",
    padding: 20,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#ccc",
    shadowColor: "#000",
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 3,
    alignItems: "center",
    justifyContent: "center",
    columnGap: 20,
  },
  textStyle: {
    fontSize: 30,
    color: "#333",
    textAlign: "center",
  },
  imageStyle: {
    flex: 1,
    height: 200,
    borderRadius: 15,
    marginTop: 50,
  },
  imageContainer: {
    flexDirection: "row",
    gap: 10,
  },
  CameraContainer: {
    flex: 1,
  },
  camera: {
    flex: 1,
  },
  CameraButtons: {
    position: "absolute",
    flexDirection: "row",
    bottom: 25,
    alignSelf: "center",
    gap: 50,
  },
  captureButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "pink",
    borderWidth: 5,
    borderColor: "gray",
  },
  permissionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  permissionButton: {
    marginTop: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: "#007AFF",
    borderRadius: 8,
  },
  permissionButtonText: {
    color: "white",
    fontWeight: "bold",
  },
  map: {
    flex: 1,
  },
  cameraButton: {
    position: "absolute",
    bottom: 40,
    right: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#3388ff",
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  cameraButtonDisabled: {
    backgroundColor: "#9e9e9e",
  },
  cameraIcon: {
    fontSize: 26,
  },
  locateButton: {
    position: "absolute",
    bottom: 116,
    right: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  locateButtonActive: {
    backgroundColor: "#3388ff",
  },
  locateIcon: {
    fontSize: 26,
  },
});
