import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  imageBackground: {
    flex: 1,
    resizeMode: 'cover',
  },
  background: {
    backgroundColor: '#E4ACEA',
  },

  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 50,
  },

  mapContainer: {
    flex: 1,
  },

  TextContainer: {
    marginTop: 50,
    alignSelf: 'center',
    width: '90%',
    padding: 20,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 20,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  textStyle: {
    fontSize: 30,
    color: '#333',
    textAlign: 'center',
    flexWrap: 'wrap',
  },
  imageStyle: {
    flex: 1,
    height: 200,
    borderRadius: 15,
    marginTop: 50,
  },
  imageContainer: {
    margin: 20,
    flexDirection: 'row',
    gap: 10,
    padding: 20,
    borderRadius: 15,
    shadowOpacity: 0.4,
    shadowRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 20,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    width: '90%',
  },
  CameraContainer: {
    flex: 1,
  },
  cameraPageContainer: {
    flex: 1,
    backgroundColor: '#222',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 40,
  },
  cameraPageBtn: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#444',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nativeCameraButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 20,
    padding: 8,
  },
  previewOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 24,
  },
  previewImage: {
    width: '90%',
    height: '65%',
    borderRadius: 12,
  },
  previewActions: {
    flexDirection: 'row',
    gap: 16,
  },
  previewBtn: {
    alignItems: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  previewBtnPrimary: {
    backgroundColor: '#3388ff',
  },
  previewBtnSecondary: {
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  previewBtnText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  camera: {
    flex: 1,
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 50,
    alignSelf: 'center',
  },
  CameraButtons: {
    position: 'absolute',
    flexDirection: 'row',
    bottom: 25,
    alignSelf: 'center',
    gap: 50,
  },
  captureButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'pink',
    borderWidth: 5,
    borderColor: 'gray',
  },
  permissionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  permissionButton: {
    marginTop: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: '#007AFF',
    borderRadius: 8,
  },
  permissionButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  map: {
    flex: 1,
  }, // värit taustalle #B5DACE, #ECC0D1
  cameraButton: {
    position: 'absolute',
    bottom: 40,
    right: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#3388ff',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  cameraButtonDisabled: {
    backgroundColor: '#9e9e9e',
  },
  cameraIcon: {
    fontSize: 26,
  },
  locateButton: {
    position: 'absolute',
    bottom: 116,
    right: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  locateButtonActive: {
    backgroundColor: '#3388ff',
  },
  locateIcon: {
    fontSize: 26,
  },
});
